
export const EXPENSE_FETCH_REQUEST = 'EXPENSE_FECTCH_REQUEST';
export const EXPENSE_FETCH_SUCCESS = 'EXPENSE_FECTCH_SUCCESS';
export const EXPENSE_FETCH_FAIL = 'EXPENSE_FECTCH_FAIL';

export const ADD_EXPENSE_REQUEST = 'ADD_EXPENSE_REQUEST';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAIL = 'ADD_EXPENSE_FAIL';

export const EDIT_EXPENSE_REQUEST = 'EDIT_EXPENSE_REQUEST';
export const EDIT_EXPENSE_SUCCESS = 'EDIT_EXPENSE_SUCCESS';
export const EDIT_EXPENSE_FAIL = 'EDIT_EXPENSE_FAIL';

export const ADD_INCOME = 'ADD_INCOME';
export const EDIT_INCOME = 'EDIT_INCOME';
export const VIEW_INCOME = 'VIEW_INCOME';
export const DELETE_INCOME = 'DELETE_INCOME';

export const ADD_USER = 'ADD_USER';
export const EDIT_USER = 'EDIT_USER';
export const VIEW_USER = 'VIEW_USER';
export const DELETE_USER = 'DELETE_USER';

export const CLICK_EXPENSE = 'CLICK_EXPENSE';
export const CLICK_INCOME = 'CLICK_INCOME';
export const CLICK_DASHBOARD = 'CLICK_DASHBOARD';
export const CLICK_ACCOUNT = 'CLICK_ACCOUNT';
export const CLICK_LOGOUT = 'CLICK_LOGOUT';

export const CATEGORY_EXPENSE_FETCH_REQUEST = 'CATEGORY_EXPENSE_FECTCH_REQUEST';
export const CATEGORY_EXPENSE_FETCH_SUCCESS = 'CATEGORY_EXPENSE_FECTCH_SUCCESS';
export const CATEGORY_EXPENSE_FETCH_FAIL = 'CATEGORY_EXPENSE_FECTCH_FAIL';

export const CURRENCY_FETCH_REQUEST = 'CURRENCY_FECTCH_REQUEST';
export const CURRENCY_FETCH_SUCCESS = 'CURRENCY_FECTCH_SUCCESS';
export const CURRENCY_FETCH_FAIL = 'CURRENCY_FECTCH_FAIL';