
export const EXPENSE_FETCH_REQUEST = 'EXPENSE_FECTCH_REQUEST';
export const EXPENSE_FETCH_SUCCESS = 'EXPENSE_FECTCH_SUCCESS';
export const EXPENSE_FETCH_FAIL = 'EXPENSE_FECTCH_FAIL';

export const ADD_EXPENSE_REQUEST = 'ADD_EXPENSE_REQUEST';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAIL = 'ADD_EXPENSE_FAIL';

export const EDIT_EXPENSE_REQUEST = 'EDIT_EXPENSE_REQUEST';
export const EDIT_EXPENSE_SUCCESS = 'EDIT_EXPENSE_SUCCESS';
export const EDIT_EXPENSE_FAIL = 'EDIT_EXPENSE_FAIL';

export const ADD_INCOME = 'ADD_INCOME';
export const EDIT_INCOME = 'EDIT_INCOME';
export const VIEW_INCOME = 'VIEW_INCOME';
export const DELETE_INCOME = 'DELETE_INCOME';


export const USER_FETCH_REQUEST = 'USER_FECTCH_REQUEST';
export const USER_FETCH_SUCCESS = 'USER_FECTCH_SUCCESS';
export const USER_FETCH_FAIL = 'USER_FECTCH_FAIL';

export const CATEGORY_EXPENSE_FETCH_REQUEST = 'CATEGORY_EXPENSE_FECTCH_REQUEST';
export const CATEGORY_EXPENSE_FETCH_SUCCESS = 'CATEGORY_EXPENSE_FECTCH_SUCCESS';
export const CATEGORY_EXPENSE_FETCH_FAIL = 'CATEGORY_EXPENSE_FECTCH_FAIL';

export const CURRENCY_FETCH_REQUEST = 'CURRENCY_FECTCH_REQUEST';
export const CURRENCY_FETCH_SUCCESS = 'CURRENCY_FECTCH_SUCCESS';
export const CURRENCY_FETCH_FAIL = 'CURRENCY_FECTCH_FAIL';